// -----------------------------------------------------------------------
// WEB PROJECTS
// -----------------------------------------------------------------------
// Same shape as branding-data.js. "url" is the live website — on the
// project's own page, clicking the title opens it in a new tab.
// -----------------------------------------------------------------------
const webProjects = [
  {
    id: "association-pierre-belon",
    title: "ASSOCIATION PIERRE BELON",
    cover: "images/web/apb_def.jpg",
    coverHover: "images/web/apb_hov.jpg",
    images: [
      "images/web/apb01.jpg",
      "images/web/apb02.jpg",
      "images/web/apb03.jpg",
      "images/web/apb04.jpg",
      "images/web/apb05.jpg",
      "images/web/apb06.jpg",
      "images/web/apb07.jpg",
      "images/web/apb08.jpg",
    ],
    url: "https://associationpierrebelon.com/",
    description: "To break away from dated scholarly norms, Association Pierre Belon, a French academic organization dedicated to Balkan and Byzantine studies, needed a modern editorial platform to engage broader audiences and showcase its print publications. Designed with full creative freedom, the platform bridges history with contemporary digital interaction. Vintage woodcut etchings paired with clean Swiss typography ground the archival material in a sleek, modern visual identity, while intuitive multi-level submenus and a high-contrast overlay menu make navigating complex historical archives effortless for every reader.",
  },
  {
    id: "kobo",
    title: "KOBO SPECIALTY COFFEE",
    cover: "images/web/kobo_def.jpg",
    coverHover: "images/web/kobo_hov.jpg",
    images: [
      "images/web/koboweb01.jpg",
      "images/web/koboweb02.jpg",
      "images/web/kobogif.gif",
      "images/web/koboweb03.jpg",
      "images/web/koboweb04.jpg",
      "images/web/koboweb05.jpg",
      "images/web/koboweb06.jpg",
      "images/web/koboweb07.jpg",
      "images/web/koboweb08.jpg",
      "images/web/koboweb09.jpg",
    ],
    url: "",
    description: "Inspired by the Japanese concept of a workshop, Kobo is an Athens-based specialty coffee store that treats brewing as a crafted ritual. The visual identity and web experience combine a clean, matcha-accented aesthetic with an interactive e-commerce platform built around the details of coffee preparation. Ambient full-screen videos, subtle micro-animations, and a 3D-inspired pop-up menu create a tactile, artisanal digital experience. The e-order page allows for precise coffee customization, while the account hub provides real-time order tracking and a digital loyalty card for in-store scanning.",
  },
 {
    id: "bakaliko-paparizos",
    title: "BAKALIKO PAPARIZOS",
    cover: "images/web/paparizos_def.jpg",
    coverHover: "images/web/paparizos_hov.jpg",
    images: [
      "images/web/paparizosweb01.jpg",
      "images/web/paparizosweb02.jpg",
      "images/web/paparizosweb03.jpg",
      "images/web/paparizosweb04.jpg",
      "images/web/paparizosweb05.jpg",
      "images/web/paparizosweb06.jpg",
      "images/web/paparizosweb07.jpg",
    ],
    url: "https://paparizos-bakaliko.gr/",
    description: "Bakaliko Paparizos is a traditional Greek deli and grocery store established in 1952, bringing together Greek products and carefully selected producers under one heritage-driven brand. The new e-commerce platform translates the familiar experience of the physical grocery into a contemporary digital environment, combining the brand’s warm and approachable character with a streamlined shopping experience. The website introduces dedicated online ordering, clearly structured product categories, and interactive browsing elements, making it easy to explore the range and move naturally from discovery to purchase.",
  },
  {
    id: "g-epsilon",
    title: "G-EPSILON PROPERTY MANAGEMENT",
    cover: "images/web/ge_def.jpg",
    coverHover: "images/web/ge_hov.jpg",
    images: [
      "images/web/geweb01.jpg",
      "images/web/geweb02.jpg",
      "images/web/geweb03.jpg",
      "images/web/geweb04.jpg",
      "images/web/geweb05.jpg",
      "images/web/geweb06.jpg",
      "images/web/geweb07.jpg",
      "images/web/geweb08.jpg",
    ],
    url: "https://gepsilon.gr/",
    description: "G-Epsilon’s visual identity and digital presence were redesigned to better position the property management firm within Athens’ evolving real estate landscape. The previous outdated website was replaced with a refined digital experience, built around a deep cobalt blue palette, strong photography, and clean typography. The new website was structured to make information easier to navigate and understand, with services, client testimonials, market insights, and properties presented through a clear visual hierarchy. Interactive overlay menus help simplify navigation, while a visual-first approach puts the properties forward without taking focus away from G-Epsilon’s core expertise in property management.",
  },
  {
    id: "dynawasp",
    title: "DYNAWASP",
    cover: "images/web/dyna_def.jpg",
    coverHover: "images/web/dyna_hov.jpg",
    images: [
      "images/web/dyna01.jpg",
      "images/web/dyna02.jpg",
      "images/web/dyna03.jpg",
      "images/web/dyna04.jpg",
      "images/web/dyna05.jpg",
      "images/web/dyna06.jpg",
      "images/web/dyna07.jpg",
      "images/web/dyna08.jpg",
    ],
    url: "https://dynawasp.com/",
    description: "DynaWasp is an Athens-based digital agency. To better reflect the firm's growing capabilities, a complete visual and structural redesign was undertaken, transforming a fragmented, illustration-heavy site into a streamlined digital showcase. Built around a vibrant, high-contrast palette, navigational friction was resolved by replacing multi-level dropdowns with a sleek overlay menu and swapping static service pages for an interactive in-page hover carousel. Portfolio projects were consolidated into a unified catalog featuring logo thumbnails with dynamic hover previews and curated, color-matched case studies, all supported by a minimal blog and a playful, guided contact form.",
  },
 {
    id: "butchers-burger",
    title: "BUTCHER'S BURGER",
    cover: "images/web/butchers_def.jpg",
    coverHover: "images/web/butchers_hov.jpg",
    images: [
      "images/web/butchersweb01.jpg",
      "images/web/butchersweb02.jpg",
      "images/web/butchersweb03.jpg",
      "images/web/butchersweb04.jpg",
      "images/web/butchersweb05.jpg",
      "images/web/butchersweb06.jpg",
      "images/web/butchersweb07.jpg",
    ],
    url: "https://butchersburger.gr/",
    description: "Butcher’s Burger is one of Athens’ premier street food destinations, renowned for its bold identity and artisanal burgers. A complete digital redesign was executed to translate the brand’s raw energy into a modern web experience, anchoring the visual system in signature black and deep red tones. This new approach puts the food front and center through dynamic visuals, subtle micro-animations, and an interactive dish gallery. By restructuring the site's layout, the design effortlessly bridges full-screen imagery with fluid navigation, delivering a sleek platform that highlights product quality while driving user engagement.",
  },
 {
    id: "taz-smash-burger",
    title: "TAZ SMASH BURGER",
    cover: "images/web/taz_def.jpg",
    coverHover: "images/web/taz_hov.jpg",
    images: [
      "images/web/tazweb01.jpg",
      "images/web/tazweb02.jpg",
      "images/web/tazweb03.jpg",
      "images/web/tazweb04.jpg",
      "images/web/tazweb05.jpg",
      "images/web/tazweb06.jpg",
    ],
    url: "https://tazsmash.gr/",
    description: "Taz Smash Burger is a street-style burger brand with a bold and playful visual identity. The website translates this character into an interactive digital experience, drawing inspiration from comic-book graphics, expressive typography, and the vibrant colors of the brand. The playful interface turns browsing into part of the experience, with an interactive burger-shaped hover overlay allowing visitors to discover the different Taz locations. Alongside this, a clean and clearly structured menu keeps the full product range and essential information easy to explore, balancing the expressive visual language with a straightforward user experience.",
  },
 {
    id: "sunday-morning-vintage",
    title: "SUNDAY MORNING VINTAGE",
    cover: "images/web/sunday_def.jpg",
    coverHover: "images/web/sunday_hov.jpg",
    images: [
      "images/web/sundayweb01.jpg",
      "images/web/sundayweb02.jpg",
      "images/web/sundayweb03.jpg",
      "images/web/sundayweb04.jpg",
      "images/web/sundayweb05.jpg",
      "images/web/sundayweb06.jpg",
      "images/web/sundayweb07.jpg",
      "images/web/sundayweb08.jpg",
      "images/web/sundayweb09.jpg",
    ],
    url: "https://sundaymorningvintage.eu/",
    description: "Sunday Morning Vintage is a concept vintage store selling objects from Greece and France. The website was designed to capture the nostalgia and character of vintage culture through a clean digital experience. A warm color palette, distinctive typography, and carefully curated product presentation create a striking digital environment while keeping the focus on the objects and their stories.",
  },
];
